### ISSUE TITLE
Compile failures due to inaccurate version bounds.

### ISSUE THREAD

**Issue by hvr** [j1r1k/portager#1]
First off, welcome to Hackage!

I have noticed that the build-dependencies specification of `portage` has inaccurate versions bounds, resulting in build failures such as 

```
Configuring library for portager-0.1.0.0..
Preprocessing library for portager-0.1.0.0..
Building library for portager-0.1.0.0..
[1 of 5] Compiling Portager.DSL     ( src/Portager/DSL.hs, /tmp/matrix-worker/1495391938/dist-newstyle/build/x86_64-linux/ghc-8.2.0.20170505/portager-0.1.0.0/build/Portager/DSL.o )
[2 of 5] Compiling Portager.Flatten ( src/Portager/Flatten.hs, /tmp/matrix-worker/1495391938/dist-newstyle/build/x86_64-linux/ghc-8.2.0.20170505/portager-0.1.0.0/build/Portager/Flatten.o )
[3 of 5] Compiling Portager.Options ( src/Portager/Options.hs, /tmp/matrix-worker/1495391938/dist-newstyle/build/x86_64-linux/ghc-8.2.0.20170505/portager-0.1.0.0/build/Portager/Options.o )

src/Portager/Options.hs:30:7: error:
    • Variable not in scope: (<>) :: Mod f4 a6 -> Mod f5 a7 -> t4
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
30 |       <> short 't'
   |       ^^

src/Portager/Options.hs:31:7: error:
    • Variable not in scope: (<>) :: t4 -> Mod f3 a5 -> t3
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
31 |       <> metavar "TARGET"
   |       ^^

src/Portager/Options.hs:32:7: error:
    • Variable not in scope: (<>) :: t3 -> Mod f2 [Char] -> t2
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
32 |       <> value "/etc/portage"
   |       ^^

src/Portager/Options.hs:33:7: error:
    • Variable not in scope: (<>) :: t2 -> Mod f1 a4 -> t1
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
33 |       <> showDefault
   |       ^^

src/Portager/Options.hs:34:7: error:
    • Variable not in scope:
        (<>) :: t1 -> Mod f0 a3 -> Mod OptionFields String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
34 |       <> help "Target directory"
   |       ^^

src/Portager/Options.hs:38:7: error:
    • Variable not in scope: (<>) :: Mod f10 a11 -> Mod f11 a12 -> t8
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
38 |       <> short 'w'
   |       ^^

src/Portager/Options.hs:39:7: error:
    • Variable not in scope: (<>) :: t8 -> Mod f9 a10 -> t7
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
39 |       <> metavar "WORLD_SETS"
   |       ^^

src/Portager/Options.hs:40:7: error:
    • Variable not in scope: (<>) :: t7 -> Mod f8 [Char] -> t6
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Options.Applicative),
        ‘*>’ (imported from Options.Applicative),
        ‘<$’ (imported from Options.Applicative)
   |
40 |       <> value "/var/lib/portage/world_sets"
   |       ^^
...
```

Please be aware that accurate version bounds are mandated by the [PVP](http://pvp.haskell.org/), and packages are expected to follow the PVP as part of the [Hackage guidelines](http://hackage.haskell.org/upload).  This has various knock off consequences, such as Hackage possibly not being able to generate Haddock documentation for your package, install-plans degrading over time, as well generally resulting in a poor experience for users since they'll risk running into the  compilation errors caused by inaccurate version bounds.

If you're using Stack, you can simply add `pvp-bounds: both` to your Stack.yaml; see also https://docs.haskellstack.org/en/stable/yaml_configuration/#pvp-bounds

If you have any questions regarding this or cabal packaging in general, please feel free to ask me!

**Comment by j1r1k** [comment]
@hvr Thanks a lot for pointing this out. I was not aware of the stack option `pvp-bounds`. It is very helpful.

It should be fixed now.

**Comment by hvr** [comment]
@j1r1k please take into account that the `.cabal` file currently says `base >= 4.7 && < 5`, so that version range is not changed by `pvp-bounds: both`. Which means that you should verify that your package is actually compatible with base-4.7 (i.e. GHC 7.8). In fact, it would currently fail with

```
src/Portager/Flatten.hs:14:8:
    Could not find module ‘Data.List.NonEmpty’
    It is a member of the hidden package ‘semigroups-0.18.3’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

src/Portager/Flatten.hs:16:8:
    Could not find module ‘Data.Semigroup’
    It is a member of the hidden package ‘semigroups-0.18.3’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

as NonEmpty & Semigroup weren't in base-4.7 yet.

As a general rule of thumb, the compatibility version range advertised on `base` should reflect the set of GHC compilers you've actually tested your package with.

**Comment by j1r1k** [comment]
@hvr Ooops, very good hint, thanks a lot. I will look into that.

**Comment by hvr** [comment]
@j1r1k Fyi, I just fixed the meta-data at https://hackage.haskell.org/package/portager-0.1.1.0/revisions/ (IOW, you don't need to upload a new release just to correct the meta-data)

**Comment by j1r1k** [comment]
@hvr Oh I didn't know that you can change metadata without new upload. Thanks a lot for that. I will fix it in the repo.

**Comment by hvr** [comment]
@j1r1k btw, do you have any suggestions how we can improve the documentation so that newcomers to Hackage notice this easier? How did you go about uploading your first package? Is http://hackage.haskell.org/upload too confusing/too much wall-of-text?

**Comment by j1r1k** [comment]
@hvr I took the liberty to message you via private means as it is no longer relevant to the issue. Once again thanks a lot for help.
